In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("train_u6lujuX_CVtuZ9i (1).csv")

In [3]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    str
 12  Loan_Status        614 non-null    str
dtypes: float64(4), int64(1), str(8)
memory usage: 62.5 KB

In [5]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [7]:
df=df.drop('Property_Area',axis=1)

In [9]:
df=df.drop('Loan_Status',axis=1)

In [10]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
dtype: int64

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             601 non-null    str
 2   Married            611 non-null    str
 3   Dependents         599 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      582 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
dtypes: float64(4), int64(1), str(6)
memory usage: 52.9 KB

In [15]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object' or df[col].dtype=='string':
            df[col]=df[col].fillna(df[col].mode()[0])
        else:
            df[col]=df[col].fillna(df[col].mean())

In [16]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
dtype: int64

For loop orqali encoding qilish one hot encoding qilish

In [20]:
for col in df.columns:
    if df[col].dtype=='str':
        dummies=pd.get_dummies(df[col],prefix=col)
        df=pd.concat([df.drop(columns=[col]),dummies],axis=1)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Columns: 631 entries, ApplicantIncome to Self_Employed_Yes
dtypes: bool(626), float64(4), int64(1)
memory usage: 399.5 KB

In [23]:
df.head()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_ID_LP001002,Loan_ID_LP001003,Loan_ID_LP001005,Loan_ID_LP001006,Loan_ID_LP001008,...,Married_No,Married_Yes,Dependents_0,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes
0,5849,0.0,146.412162,360.0,1.0,True,False,False,False,False,...,True,False,True,False,False,False,True,False,True,False
1,4583,1508.0,128.000000,360.0,1.0,False,True,False,False,False,...,False,True,False,True,False,False,True,False,True,False
2,3000,0.0,66.000000,360.0,1.0,False,False,True,False,False,...,False,True,True,False,False,False,True,False,False,True
3,2583,2358.0,120.000000,360.0,1.0,False,False,False,True,False,...,False,True,True,False,False,False,False,True,True,False
4,6000,0.0,141.000000,360.0,1.0,False,False,False,False,True,...,True,False,True,False,False,False,True,False,True,False

for loop orqali Label encoding qilish

In [38]:
df=pd.read_csv("train_u6lujuX_CVtuZ9i (1).csv")

In [39]:
df=df.drop('Property_Area',axis=1)

In [40]:
df=df.drop('Loan_Status',axis=1)

In [41]:
for col in df.columns:
    if df[col].isnull().any():
        if df[col].dtype=='object' or df[col].dtype=='string':
            df[col]=df[col].fillna(df[col].mode()[0])
        else:
            df[col]=df[col].fillna(df[col].mean())

In [44]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
dtype: int64

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    str
 1   Gender             614 non-null    str
 2   Married            614 non-null    str
 3   Dependents         614 non-null    str
 4   Education          614 non-null    str
 5   Self_Employed      614 non-null    str
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
dtypes: float64(4), int64(1), str(6)
memory usage: 52.9 KB

In [57]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

for col in df.columns:
    if df[col].dtype=='object' or df[col].dtype=='str' :
        df[col]=label.fit_transform(df[col])

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    int64
 1   Gender             614 non-null    int64
 2   Married            614 non-null    int64
 3   Dependents         614 non-null    int64
 4   Education          614 non-null    int64
 5   Self_Employed      614 non-null    int64
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
dtypes: float64(4), int64(7)
memory usage: 52.9 KB

In [59]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,0,1,0,0,0,0,5849,0.0,146.412162,360.0,1.0
1,1,1,1,1,0,0,4583,1508.0,128.000000,360.0,1.0
2,2,1,1,0,0,1,3000,0.0,66.000000,360.0,1.0
3,3,1,1,0,1,0,2583,2358.0,120.000000,360.0,1.0
4,4,1,0,0,0,0,6000,0.0,141.000000,360.0,1.0

Scaling qilish 3 ta usulda

In [60]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler

In [61]:
num_col=df.select_dtypes(include=['int64','float64'])

In [63]:
scaler=StandardScaler()

In [64]:
scaler

StandardScaler()

In [65]:
df['ApplicantIncome']=scaler.fit_transform(df[['ApplicantIncome']])

In [66]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,0,1,0,0,0,0,0.072991,0.0,146.412162,360.0,1.0
1,1,1,1,1,0,0,-0.134412,1508.0,128.000000,360.0,1.0
2,2,1,1,0,0,1,-0.393747,0.0,66.000000,360.0,1.0
3,3,1,1,0,1,0,-0.462062,2358.0,120.000000,360.0,1.0
4,4,1,0,0,0,0,0.097728,0.0,141.000000,360.0,1.0

MinMax scaler

In [67]:
scaler=MinMaxScaler()

In [68]:
scaler

MinMaxScaler()

In [69]:
df['LoanAmount']=scaler.fit_transform(df[['LoanAmount']])

In [70]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,0,1,0,0,0,0,0.072991,0.0,0.198860,360.0,1.0
1,1,1,1,1,0,0,-0.134412,1508.0,0.172214,360.0,1.0
2,2,1,1,0,0,1,-0.393747,0.0,0.082489,360.0,1.0
3,3,1,1,0,1,0,-0.462062,2358.0,0.160637,360.0,1.0
4,4,1,0,0,0,0,0.097728,0.0,0.191027,360.0,1.0

RobustScaler

In [71]:
scaler=RobustScaler()

In [72]:
df['CoapplicantIncome']=scaler.fit_transform(df[['CoapplicantIncome']])

In [73]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,0,1,0,0,0,0,0.072991,-0.517358,0.198860,360.0,1.0
1,1,1,1,1,0,0,-0.134412,0.139079,0.172214,360.0,1.0
2,2,1,1,0,0,1,-0.393747,-0.517358,0.082489,360.0,1.0
3,3,1,1,0,1,0,-0.462062,0.509087,0.160637,360.0,1.0
4,4,1,0,0,0,0,0.097728,-0.517358,0.191027,360.0,1.0

for loop orqali MinMax scalerda

In [74]:
scaler=MinMaxScaler()
for col in df.columns:
    if df[col].dtype!='object' or df[col].dtype!='str':
        df[col]=scaler.fit_transform(df[[col]])

In [75]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
0,0.000000,1.0,0.0,0.000000,0.0,0.0,0.070489,0.000000,0.198860,0.74359,1.0
1,0.001631,1.0,1.0,0.333333,0.0,0.0,0.054830,0.036192,0.172214,0.74359,1.0
2,0.003263,1.0,1.0,0.000000,0.0,1.0,0.035250,0.000000,0.082489,0.74359,1.0
3,0.004894,1.0,1.0,0.000000,1.0,0.0,0.030093,0.056592,0.160637,0.74359,1.0
4,0.006525,1.0,0.0,0.000000,0.0,0.0,0.072356,0.000000,0.191027,0.74359,1.0