1. Agar berilgan son 2 ga bo’linsa yaxshi aks xolda yomon degan sozni ekrang chiqaring?

In [ ]:
a = int(input(" Sonni kiriting: "))
if a%2==0:
    print('Yaxshi ')
else:
    print('Yomon ')

2. Agar berilgan son musbat bo’lsa yaxshi aks xolda yomon degan sozni ekrang chiqaring?

In [ ]:
a=int(input('Son kiriting '))
if a>=0:
    print('Yaxshi')
else:
    print('Yomon')

Yomon

3. Agar berilgan 5 ga va 3 ga bolinsa yaxshi aks xolda yomon degan sozni ekrang chiqaring?

In [ ]:
a=int(input('Son kiriting '))
if a%3==0 and a%5==0:
    print('Yaxshi')
else:
    print('Yomon')

Yaxshi

4. Agar berilgan so’zning bosh xarfi ‘a’ bolsa yaxshi aks xolda yomon degan sozni ekrang chiqaring

In [ ]:
a=input(" Matn kiriting ")
if a[0]=='a' or a[0]=='A':
    print('Yaxshi')
else:
    print('Yomon')

Yaxshi

5. Agar berilgan so’zning oxirgi xarfi ‘a’ bolsa yaxshi aks xolda yomon degan sozni ekrang chiqaring

In [ ]:
a=input('Matn kiriting')
if a[-1]=='a':
    print('Yaxshi')
else:
    print('Yomon')

Yaxshi

6. Agar berilgan so’zning bosh xarfi ‘b’ va oxirgi xarfi ‘a’ bolsa yaxshi aks xolda yomon degan sozni ekrang chiqaring

In [ ]:
a=input('Matn kiriting')
if a[0]=='b' or a[0]=='B' and a[-1]=='a':
    print('Yaxshi')
else:
    print('Yomon')

Yomon

7. Berilgan sonning musbat ekanligini isbotlang

In [ ]:
a=int(input('Son kiriting '))
if a>=0:
    print('Musbat son')
else:
    print('Manfiy son')

Manfiy son

8. Berilgan sonning manfiy ekanligini isbotlang

In [ ]:
a=int(input('Son kiriting '))
if a<0:
    print('Manfiy son')
else:
    print('Musbat son')

Manfiy son

9. Berilgan sonning nol ekanligini isbotlang

In [ ]:
a=int(input('Son kiriting '))
if a==0:
    print('Nolga teng')
else:
    print('Boshqa son')

10. Berilgan sonning 2 ga bolinishini isbotlang

In [ ]:
a=int(input('Sonni kiriting '))
if a%2==0:
    print('Bu son ikkiga bolinadi')
else:
    print('Bu son ikkiga bolinmaydi')

Bu son ikkiga bolinadi

ML coding

In [22]:
import pandas as pd

In [23]:
df=pd.read_csv('titanic_data.csv')

In [24]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    str
 3   age          713 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     887 non-null    str
 8   class        889 non-null    str
 9   who          889 non-null    str
 10  adult_male   889 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  887 non-null    str
 13  alive        889 non-null    str
 14  alone        889 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.2 KB

In [26]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            176
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [27]:
df['embarked']=df['embarked'].fillna(df['embarked'].mode()[0])

In [28]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            176
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [29]:
df['age']=df['age'].fillna(df['age'].mean())

In [30]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [31]:
df['embark_town']=df['embark_town'].fillna('New york')

In [32]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           686
embark_town      0
alive            0
alone            0
dtype: int64

In [33]:
df = df.drop('deck',axis=1)

In [34]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

Qatorlar bo'yicha

In [41]:
import pandas as pd

In [42]:
df=pd.read_csv('titanic_data.csv')

In [43]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    str
 3   age          713 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     887 non-null    str
 8   class        889 non-null    str
 9   who          889 non-null    str
 10  adult_male   889 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  887 non-null    str
 13  alive        889 non-null    str
 14  alone        889 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.2 KB

In [45]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            176
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [46]:
df=df.T.fillna(df.mode(axis=1)[0]).T

In [47]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64