In [37]:
import pandas as pd

In [38]:
df=pd.read_csv('titanic_data.csv')

In [39]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [40]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            176
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    str
 3   age          713 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   embarked     887 non-null    str
 8   class        889 non-null    str
 9   who          889 non-null    str
 10  adult_male   889 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  887 non-null    str
 13  alive        889 non-null    str
 14  alone        889 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.2 KB

In [42]:
df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [43]:
df['age']=df['age'].fillna(df['age'].mean())

In [44]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [45]:
df['embarked']=df['embarked'].fillna(df['embarked'].mode()[0])

In [46]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           686
embark_town      2
alive            0
alone            0
dtype: int64

In [47]:
df=df.drop(['deck'],axis=1)

In [48]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [49]:
df['embark_town'] = df['embark_town'].fillna('Southampton')

In [50]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [51]:
dummies=pd.get_dummies(df['sex'],prefix='ustun',dtype=int)

In [52]:
dummies

     ustun_female  ustun_male
0               0           1
1               1           0
2               1           0
3               1           0
4               0           1
..            ...         ...
884             0           1
885             1           0
886             1           0
887             0           1
888             0           1

[889 rows x 2 columns]

In [53]:
df=pd.concat([df.drop(columns=['sex']),dummies],axis=1)

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      889 non-null    int64
 1   pclass        889 non-null    int64
 2   age           889 non-null    float64
 3   sibsp         889 non-null    int64
 4   parch         889 non-null    int64
 5   fare          889 non-null    float64
 6   embarked      889 non-null    str
 7   class         889 non-null    str
 8   who           889 non-null    str
 9   adult_male    889 non-null    bool
 10  embark_town   889 non-null    str
 11  alive         889 non-null    str
 12  alone         889 non-null    bool
 13  ustun_female  889 non-null    int64
 14  ustun_male    889 non-null    int64
dtypes: bool(2), float64(2), int64(6), str(5)
memory usage: 92.2 KB

In [58]:
dummies=pd.get_dummies(df['embarked'],prefix='ustun',dtype=int)

In [60]:
df=pd.concat([df.drop(columns=['embarked']),dummies],axis=1)

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      889 non-null    int64
 1   pclass        889 non-null    int64
 2   age           889 non-null    float64
 3   sibsp         889 non-null    int64
 4   parch         889 non-null    int64
 5   fare          889 non-null    float64
 6   class         889 non-null    str
 7   who           889 non-null    str
 8   adult_male    889 non-null    bool
 9   embark_town   889 non-null    str
 10  alive         889 non-null    str
 11  alone         889 non-null    bool
 12  ustun_female  889 non-null    int64
 13  ustun_male    889 non-null    int64
 14  ustun_C       889 non-null    int64
 15  ustun_Q       889 non-null    int64
 16  ustun_S       889 non-null    int64
dtypes: bool(2), float64(2), int64(9), str(4)
memory usage: 106.0 KB

In [63]:
dummies=pd.get_dummies(df['class'],prefix='ustun',dtype=int)
df=pd.concat([df.drop(columns='class'),dummies],axis=1)

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      889 non-null    int64
 1   pclass        889 non-null    int64
 2   age           889 non-null    float64
 3   sibsp         889 non-null    int64
 4   parch         889 non-null    int64
 5   fare          889 non-null    float64
 6   who           889 non-null    str
 7   adult_male    889 non-null    bool
 8   embark_town   889 non-null    str
 9   alive         889 non-null    str
 10  alone         889 non-null    bool
 11  ustun_female  889 non-null    int64
 12  ustun_male    889 non-null    int64
 13  ustun_C       889 non-null    int64
 14  ustun_Q       889 non-null    int64
 15  ustun_S       889 non-null    int64
 16  ustun_First   889 non-null    int64
 17  ustun_Second  889 non-null    int64
 18  ustun_Third   889 non-null    int64
dtypes: bool(2), float64(2), int64(12), str(3)
memory usage: 119.9 KB

In [72]:

from sklearn.preprocessing import LabelEncoder

In [73]:
encoder=LabelEncoder()

In [74]:
encoder

LabelEncoder()

In [75]:
df['who']=encoder.fit_transform(df['who'])

In [77]:
df['adult_male']=encoder.fit_transform(df['adult_male'])

In [78]:
df['embark_town']=encoder.fit_transform(df['embark_town'])

In [80]:
df['alive']=encoder.fit_transform(df['alive'])

In [81]:
df['alone']=encoder.fit_transform(df['alone'])

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 889 entries, 0 to 888
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   survived      889 non-null    int64
 1   pclass        889 non-null    int64
 2   age           889 non-null    float64
 3   sibsp         889 non-null    int64
 4   parch         889 non-null    int64
 5   fare          889 non-null    float64
 6   who           889 non-null    int64
 7   adult_male    889 non-null    int64
 8   embark_town   889 non-null    int64
 9   alive         889 non-null    int64
 10  alone         889 non-null    int64
 11  ustun_female  889 non-null    int64
 12  ustun_male    889 non-null    int64
 13  ustun_C       889 non-null    int64
 14  ustun_Q       889 non-null    int64
 15  ustun_S       889 non-null    int64
 16  ustun_First   889 non-null    int64
 17  ustun_Second  889 non-null    int64
 18  ustun_Third   889 non-null    int64
dtypes: float64(2), int64(17)
memory usage: 132.1 KB